services:
  ctrader-bot:
    build: .
    container_name: ctrader-bot
    ports:
      - "8000:8000"
    restart: always

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    entrypoint: ["ngrok", "http", "--log", "stdout", "--authtoken", "<NGROK_TOKEN>", "ctrader-bot:8000"]
    depends_on:
      - ctrader-bot
    ports:
      - "4040:4040"
